export interface GlossaryTerm {
    id: string;
    term: string;
    shortDesc: string;
    fullDesc: string;
    category: GlossaryCategory;
    related?: string[];  // ids of related terms
}

export type GlossaryCategory = 'training' | 'race' | 'body' | 'gear' | 'nutrition';

export const categoryLabels: Record<GlossaryCategory, string> = {
    training: '훈련',
    race: '대회',
    body: '신체/체력',
    gear: '장비',
    nutrition: '영양',
};

export const categoryColors: Record<GlossaryCategory, string> = {
    training: 'badge-primary',
    race: 'badge-secondary',
    body: 'badge-error',
    gear: 'badge-warning',
    nutrition: 'badge-success',
};

export const glossaryTerms: GlossaryTerm[] = [
    // Training
    {
        id: 'lsd',
        term: 'LSD (Long Slow Distance)',
        shortDesc: '장거리 저강도 달리기',
        fullDesc: '편안한 페이스로 긴 거리를 달리는 훈련 방법입니다. 유산소 지구력의 기초를 쌓는 가장 중요한 훈련으로, 대화가 가능한 정도의 속도로 60분~3시간 이상 달립니다. 마라톤 훈련의 핵심이며, 주 1회 실시하는 "롱런"이 대표적인 LSD 훈련입니다.',
        category: 'training',
        related: ['easy-run', 'long-run', 'aerobic'],
    },
    {
        id: 'interval',
        term: '인터벌 (Interval Training)',
        shortDesc: '고강도 반복 훈련',
        fullDesc: '빠른 속도의 달리기와 회복 조깅을 번갈아 반복하는 훈련입니다. 예: 1000m 빠르게 달리기 + 400m 조깅 회복을 5세트 반복. VO2max(최대산소섭취량)를 향상시키는 데 매우 효과적이며, 주 1~2회 실시합니다. 레이스 페이스보다 빠른 속도로 훈련하여 스피드와 심폐 능력을 동시에 기릅니다.',
        category: 'training',
        related: ['vo2max', 'tempo-run', 'fartlek'],
    },
    {
        id: 'tempo-run',
        term: '템포런 (Tempo Run)',
        shortDesc: '젖산역치 페이스 달리기',
        fullDesc: '"편하게 힘든" 정도의 강도로 20~40분간 유지하는 달리기입니다. 젖산역치(LT) 부근의 페이스로 달려 젖산 처리 능력을 향상시킵니다. 마라톤 페이스보다 km당 20~30초 정도 빠른 속도가 일반적입니다. 레이스에서 더 오래 빠른 페이스를 유지할 수 있게 해주는 핵심 훈련입니다.',
        category: 'training',
        related: ['lactate-threshold', 'interval', 'race-pace'],
    },
    {
        id: 'fartlek',
        term: '파틀렉 (Fartlek)',
        shortDesc: '자유로운 속도 변화 훈련',
        fullDesc: '스웨덴어로 "속도 놀이"라는 뜻입니다. 정해진 구간이나 시간 없이 자유롭게 빠르기를 바꿔가며 달리는 훈련입니다. 예: 전신주까지 빠르게, 다음 전신주까지 천천히. 인터벌의 딱딱함 없이 스피드 감각을 기르고, 실제 레이스에서의 페이스 변화에 적응하는 데 도움됩니다.',
        category: 'training',
        related: ['interval', 'tempo-run'],
    },
    {
        id: 'easy-run',
        term: '이지런 (Easy Run)',
        shortDesc: '편안한 회복 달리기',
        fullDesc: '대화가 가능한 편안한 페이스로 달리는 훈련입니다. 전체 훈련량의 70~80%를 차지해야 하는 가장 기본적인 훈련입니다. 근육과 심혈관 시스템의 회복을 돕고, 유산소 기초 체력을 쌓습니다. 보통 최대심박수의 60~70% 수준으로 달립니다.',
        category: 'training',
        related: ['lsd', 'heart-rate-zone'],
    },
    {
        id: 'long-run',
        term: '롱런 (Long Run)',
        shortDesc: '주간 최장거리 달리기',
        fullDesc: '일주일 중 가장 긴 거리를 달리는 훈련으로, 보통 주말에 실시합니다. 마라톤 준비 시 최대 30~35km까지 늘리며, 이지런 페이스나 약간 빠른 페이스로 달립니다. 지구력, 근지구력, 글리코겐 저장 능력, 정신력을 동시에 훈련합니다.',
        category: 'training',
        related: ['lsd', 'easy-run', 'wall'],
    },
    {
        id: 'race-pace',
        term: '레이스 페이스 (Race Pace)',
        shortDesc: '목표 대회 완주 페이스',
        fullDesc: '대회에서 목표 시간을 달성하기 위해 유지해야 하는 km당 페이스입니다. 예: 풀마라톤 서브4 목표라면 레이스 페이스는 약 5:41/km. 레이스 페이스로 달리는 훈련은 실제 대회 감각을 익히고 목표 페이스에 대한 자신감을 키우는 데 중요합니다.',
        category: 'training',
        related: ['negative-split', 'even-split'],
    },
    {
        id: 'taper',
        term: '테이퍼 (Taper)',
        shortDesc: '대회 전 훈련량 감소 기간',
        fullDesc: '대회 2~3주 전부터 훈련량(거리)을 점진적으로 줄이는 기간입니다. 강도는 유지하되 볼륨을 50~70% 줄여 몸이 완전히 회복되고 최상의 컨디션으로 대회에 임할 수 있게 합니다. 테이퍼 기간에 불안해하는 러너가 많지만, 과학적으로 기록 향상에 필수적인 과정입니다.',
        category: 'training',
        related: ['carb-loading', 'race-pace'],
    },
    {
        id: 'cross-training',
        term: '교차훈련 (Cross Training)',
        shortDesc: '달리기 외 보조 운동',
        fullDesc: '수영, 자전거, 근력운동 등 달리기가 아닌 운동을 통해 전체적인 체력을 향상시키는 훈련입니다. 달리기로 인한 부상 위험을 줄이고, 달리기에서 사용하지 않는 근육을 강화하며, 정신적 피로를 방지합니다.',
        category: 'training',
        related: ['easy-run'],
    },
    {
        id: 'hill-training',
        term: '힐 트레이닝 (Hill Training)',
        shortDesc: '오르막 반복 훈련',
        fullDesc: '오르막길을 반복해서 달리는 훈련입니다. 100~400m 오르막을 강하게 달리고 내리막에서 회복하는 것을 반복합니다. 하체 근력, 심폐 능력, 달리기 폼을 동시에 개선하는 효율적인 훈련으로, "변장한 스피드 훈련"이라 불립니다. 부상 위험이 인터벌보다 낮아 초보자에게도 추천됩니다.',
        category: 'training',
        related: ['interval', 'cadence'],
    },
    {
        id: 'strides',
        term: '스트라이드 (Strides)',
        shortDesc: '짧은 가속 달리기',
        fullDesc: '80~100m를 점진적으로 가속하여 최대 속도의 90~95%까지 올린 뒤 감속하는 짧은 달리기입니다. 이지런 후에 4~6회 실시하며, 러닝 폼 교정, 신경근 활성화, 달리기 효율 향상에 효과적입니다. 인터벌처럼 힘들지 않으면서 스피드 감각을 유지할 수 있습니다.',
        category: 'training',
        related: ['easy-run', 'cadence'],
    },
    {
        id: 'warmup-cooldown',
        term: '워밍업 / 쿨다운',
        shortDesc: '운동 전후 준비 및 정리 운동',
        fullDesc: '워밍업은 본 운동 전 10~15분간 가벼운 조깅과 동적 스트레칭으로 몸을 준비하는 과정입니다. 쿨다운은 운동 후 5~10분간 서서히 속도를 줄이고 정적 스트레칭으로 마무리하는 과정입니다. 부상 예방과 회복 촉진에 필수적이며, 특히 인터벌이나 템포런 전후에 반드시 실시해야 합니다.',
        category: 'training',
        related: ['easy-run', 'interval', 'tempo-run'],
    },
    {
        id: 'recovery-run',
        term: '리커버리 런 (Recovery Run)',
        shortDesc: '회복을 위한 가벼운 달리기',
        fullDesc: '강도 높은 훈련이나 대회 다음 날 실시하는 매우 가벼운 달리기입니다. 이지런보다 더 느린 페이스로 20~30분 정도 달리며, 혈액 순환을 촉진하여 근육 회복을 돕습니다. 무리하면 오히려 역효과가 나므로 "너무 느린 것 같다"는 느낌이 적절합니다.',
        category: 'training',
        related: ['easy-run', 'overtraining'],
    },
    {
        id: 'yasso-800',
        term: '야소 800 (Yasso 800s)',
        shortDesc: '마라톤 기록 예측 훈련법',
        fullDesc: 'Runner\'s World 편집장 Bart Yasso가 고안한 훈련법입니다. 800m를 10회 반복하되, 800m 소요 시간(분:초)이 풀마라톤 목표 시간(시:분)과 같아야 합니다. 예: 풀마라톤 3시간 30분 목표라면 800m를 3분 30초에 10회 달리기. 마라톤 준비도를 확인하는 벤치마크 훈련으로 널리 사용됩니다.',
        category: 'training',
        related: ['interval', 'race-pace'],
    },
    {
        id: 'ten-percent-rule',
        term: '10% 룰 (10% Rule)',
        shortDesc: '주간 훈련량 증가 제한 원칙',
        fullDesc: '부상 예방을 위해 주간 총 달리기 거리를 전주 대비 10% 이상 늘리지 않는 원칙입니다. 예: 이번 주 40km를 달렸다면 다음 주는 최대 44km. 근육, 힘줄, 뼈가 증가된 부하에 적응할 시간이 필요하기 때문입니다. 초보 러너에게 특히 중요한 원칙입니다.',
        category: 'training',
        related: ['runners-knee', 'overtraining'],
    },
    {
        id: 'periodization',
        term: '주기화 (Periodization)',
        shortDesc: '체계적 훈련 단계 구분',
        fullDesc: '훈련을 기초(Base), 강화(Build), 정점(Peak), 테이퍼(Taper) 등의 단계로 나누어 체계적으로 진행하는 방법입니다. 각 단계마다 훈련의 목적과 강도가 다르며, 대회일에 맞춰 최상의 컨디션을 만들어냅니다. 12~16주 마라톤 훈련 프로그램이 대표적인 주기화 훈련입니다.',
        category: 'training',
        related: ['taper', 'long-run'],
    },
    {
        id: 'base-building',
        term: '베이스 빌딩 (Base Building)',
        shortDesc: '유산소 기초 체력 구축 단계',
        fullDesc: '본격적인 대회 훈련에 앞서 유산소 기초 체력을 쌓는 4~8주의 기간입니다. 이지런과 롱런 위주로 훈련하며, 인터벌이나 템포런 같은 고강도 훈련은 최소화합니다. 탄탄한 베이스가 없으면 이후 강화 훈련에서 부상 위험이 높아집니다.',
        category: 'training',
        related: ['easy-run', 'lsd', 'periodization'],
    },
    {
        id: 'brick-training',
        term: '브릭 훈련 (Brick Training)',
        shortDesc: '두 종목을 연이어 하는 복합 훈련',
        fullDesc: '주로 철인3종에서 사용되는 훈련으로, 자전거 직후 바로 달리기를 이어서 하는 것입니다. 자전거에서 달리기로 전환할 때 다리가 벽돌처럼 무거운 느낌(brick legs)에 적응하기 위한 훈련입니다. 수영→자전거, 자전거→달리기 등의 조합으로 실시합니다.',
        category: 'training',
        related: ['cross-training'],
    },

    // Race
    {
        id: 'negative-split',
        term: '네거티브 스플릿 (Negative Split)',
        shortDesc: '후반부를 전반부보다 빠르게 달리는 전략',
        fullDesc: '레이스에서 후반부를 전반부보다 빠르게 달리는 페이스 전략입니다. 예: 풀마라톤에서 전반 21km를 2:02에, 후반 21km를 1:58에 완주. 세계 기록 대부분이 네거티브 스플릿으로 달성되었습니다. 초반에 에너지를 아끼고 후반에 힘을 낼 수 있어 가장 효율적인 레이스 전략으로 알려져 있습니다.',
        category: 'race',
        related: ['even-split', 'race-pace', 'wall'],
    },
    {
        id: 'even-split',
        term: '이븐 스플릿 (Even Split)',
        shortDesc: '전반부와 후반부를 같은 페이스로 달리는 전략',
        fullDesc: '레이스 전반부와 후반부의 페이스를 거의 동일하게 유지하는 전략입니다. 네거티브 스플릿과 함께 가장 안정적인 레이스 전략으로, 일정한 페이스를 유지하여 에너지를 효율적으로 사용합니다.',
        category: 'race',
        related: ['negative-split', 'race-pace'],
    },
    {
        id: 'dns',
        term: 'DNS (Did Not Start)',
        shortDesc: '출발하지 않음',
        fullDesc: '대회에 등록했지만 출발선에 서지 않은 것을 의미합니다. 부상, 컨디션 불량, 날씨 등의 이유로 발생합니다. 무리해서 출전하기보다 DNS를 선택하는 것이 현명한 판단이 될 수 있습니다.',
        category: 'race',
        related: ['dnf'],
    },
    {
        id: 'dnf',
        term: 'DNF (Did Not Finish)',
        shortDesc: '완주하지 못함',
        fullDesc: '대회에 출발했지만 완주하지 못한 것을 의미합니다. 부상, 탈진, 컷오프 시간 초과 등의 이유로 발생합니다. DNF 역시 용기 있는 결정이며, 부상 방지를 위해 필요한 경우가 있습니다.',
        category: 'race',
        related: ['dns', 'wall'],
    },
    {
        id: 'pb-pr',
        term: 'PB / PR (Personal Best / Record)',
        shortDesc: '개인 최고 기록',
        fullDesc: 'PB(Personal Best) 또는 PR(Personal Record)은 특정 거리에서의 개인 최고 기록을 의미합니다. 러너들의 주요 동기부여 요소이며, "PB를 깼다"는 기록을 경신했다는 뜻입니다.',
        category: 'race',
        related: ['bq'],
    },
    {
        id: 'bq',
        term: 'BQ (Boston Qualifier)',
        shortDesc: '보스턴 마라톤 자격 기록',
        fullDesc: '세계에서 가장 유명한 보스턴 마라톤 참가 자격 기준 기록입니다. 나이와 성별에 따라 다르며, 예: 18~34세 남성 기준 3시간 0분. 많은 시민 러너들의 궁극적인 목표이며, BQ를 달성하는 것 자체가 큰 성취로 여겨집니다.',
        category: 'race',
        related: ['pb-pr'],
    },
    {
        id: 'aid-station',
        term: '에이드 스테이션 (Aid Station)',
        shortDesc: '급수/급식 지점',
        fullDesc: '대회 코스 중간중간에 설치된 물, 스포츠 음료, 에너지젤 등을 제공하는 지점입니다. 보통 2~5km 간격으로 설치되며, 울트라마라톤에서는 식사까지 제공됩니다. 급수 지점에서 속도를 줄이지 않고 컵을 집는 연습도 중요합니다.',
        category: 'race',
        related: ['carb-loading', 'energy-gel'],
    },
    {
        id: 'wall',
        term: '벽 (The Wall / Bonking)',
        shortDesc: '글리코겐 고갈로 인한 급격한 체력 저하',
        fullDesc: '마라톤에서 보통 30~35km 부근에서 겪는 급격한 체력 저하 현상입니다. 근육 내 글리코겐(탄수화물 에너지)이 고갈되면서 발생합니다. 다리가 무겁고, 페이스가 급격히 떨어지며, 정신적으로도 힘들어집니다. 충분한 롱런 훈련과 레이스 중 에너지 보충으로 예방할 수 있습니다.',
        category: 'race',
        related: ['carb-loading', 'energy-gel', 'long-run'],
    },
    {
        id: 'pacer',
        term: '페이서 / 토끼 (Pacer)',
        shortDesc: '목표 기록 완주를 도와주는 주자',
        fullDesc: '대회에서 특정 목표 시간(예: 서브4, 서브3:30)에 맞춰 일정한 페이스로 달려주는 자원봉사 주자입니다. 페이서를 따라가면 페이스 관리 부담 없이 목표 기록에 도전할 수 있습니다. 보통 풍선이나 깃발로 표시하며, "토끼"라고도 불립니다.',
        category: 'race',
        related: ['race-pace', 'even-split'],
    },
    {
        id: 'cutoff',
        term: '컷오프 타임 (Cut-off Time)',
        shortDesc: '제한 시간',
        fullDesc: '대회에서 정해진 완주 제한 시간입니다. 풀마라톤은 보통 5~6시간, 울트라마라톤은 코스별로 다릅니다. 중간 컷오프도 있어 특정 지점을 정해진 시간 내에 통과해야 합니다. 컷오프 시간을 초과하면 DNF 처리됩니다.',
        category: 'race',
        related: ['dnf', 'pacer'],
    },
    {
        id: 'net-gross-time',
        term: '넷 타임 / 그로스 타임',
        shortDesc: '실제 달린 시간 vs 총 경과 시간',
        fullDesc: '그로스 타임(Gun Time)은 출발 총성부터 결승선까지의 시간이고, 넷 타임(Chip Time)은 본인이 출발선을 지난 순간부터의 시간입니다. 대규모 대회에서는 출발까지 수분이 걸리므로 두 시간의 차이가 큽니다. 공식 기록은 보통 넷 타임을 사용하지만, 순위는 그로스 타임 기준인 대회도 있습니다.',
        category: 'race',
        related: ['pb-pr', 'wave-start'],
    },
    {
        id: 'wave-start',
        term: '웨이브 스타트 (Wave Start)',
        shortDesc: '시차를 두고 그룹별 출발',
        fullDesc: '대규모 대회에서 참가자를 예상 기록이나 신청 순서에 따라 여러 그룹(웨이브)으로 나누어 시간 차를 두고 출발시키는 방식입니다. 출발 지점의 혼잡을 줄이고, 안전하고 원활한 레이스 진행을 위해 사용됩니다.',
        category: 'race',
        related: ['net-gross-time', 'bib'],
    },
    {
        id: 'bib',
        term: '배번 (Bib Number)',
        shortDesc: '레이스 참가 번호표',
        fullDesc: '대회에서 가슴이나 허리에 부착하는 참가 번호표입니다. 타이밍 칩이 내장된 경우가 많아 기록 측정에 사용됩니다. 배번을 접거나 가리면 기록이 측정되지 않을 수 있으므로 주의해야 합니다. 안전핀이나 배번 벨트로 고정합니다.',
        category: 'race',
        related: ['net-gross-time'],
    },
    {
        id: 'expo',
        term: '엑스포 (Race Expo)',
        shortDesc: '대회 전 참가자 등록 행사',
        fullDesc: '대회 전날 또는 며칠 전에 열리는 행사로, 배번과 참가 물품을 수령하는 곳입니다. 러닝 용품 브랜드 부스, 할인 판매, 세미나 등이 함께 진행됩니다. 대회 당일에는 수령이 불가능한 경우가 대부분이므로 반드시 엑스포 기간에 방문해야 합니다.',
        category: 'race',
        related: ['bib'],
    },
    {
        id: 'ultra-marathon',
        term: '울트라마라톤 (Ultra Marathon)',
        shortDesc: '42.195km 이상의 초장거리 달리기 대회',
        fullDesc: '풀마라톤(42.195km)보다 긴 거리를 달리는 대회의 총칭입니다. 50km, 100km, 100마일(161km) 등의 거리가 있으며, 산악 코스에서 열리는 트레일 울트라도 인기입니다. 수십 시간 동안 밤을 새워 달리기도 하며, 식사, 수면 관리, 정신력이 핵심입니다.',
        category: 'race',
        related: ['aid-station', 'cutoff', 'wall'],
    },
    {
        id: 'course-record',
        term: '코스 레코드 (Course Record / CR)',
        shortDesc: '특정 대회 코스 최고 기록',
        fullDesc: '특정 대회 코스에서 달성된 역대 최고 기록입니다. 코스마다 고저차, 기후, 코스 형태가 다르므로 코스 레코드는 그 대회만의 기준이 됩니다. 세계기록(WR), 한국기록(KR)과 구분됩니다.',
        category: 'race',
        related: ['pb-pr'],
    },

    // Body
    {
        id: 'vo2max',
        term: 'VO2max (최대산소섭취량)',
        shortDesc: '유산소 능력의 지표',
        fullDesc: '운동 중 몸이 사용할 수 있는 최대 산소량(ml/kg/min)으로, 유산소 체력의 가장 중요한 지표입니다. 일반 성인 남성 평균 약 40~45, 엘리트 마라톤 선수는 70~85 수준입니다. 인터벌 훈련으로 가장 효과적으로 향상시킬 수 있으며, 유전적 상한선이 있지만 대부분의 시민 러너는 훈련으로 크게 향상 가능합니다.',
        category: 'body',
        related: ['interval', 'lactate-threshold', 'heart-rate-zone'],
    },
    {
        id: 'lactate-threshold',
        term: '젖산역치 (Lactate Threshold)',
        shortDesc: '젖산이 급격히 쌓이기 시작하는 운동 강도',
        fullDesc: '운동 강도가 높아질 때, 젖산(lactate)이 제거 속도보다 빠르게 축적되기 시작하는 지점입니다. 이 지점의 페이스를 오래 유지할수록 마라톤 기록이 좋아집니다. 템포런이 젖산역치를 향상시키는 대표적인 훈련이며, 보통 최대심박수의 80~90% 수준입니다.',
        category: 'body',
        related: ['tempo-run', 'vo2max', 'heart-rate-zone'],
    },
    {
        id: 'heart-rate-zone',
        term: '심박 존 (Heart Rate Zone)',
        shortDesc: '심박수 기반 훈련 강도 구간',
        fullDesc: '최대심박수를 기준으로 5개 구간으로 나눈 훈련 강도 체계입니다. Zone 1(50~60%): 회복, Zone 2(60~70%): 유산소 기초, Zone 3(70~80%): 유산소 강화, Zone 4(80~90%): 젖산역치, Zone 5(90~100%): 최대 강도. 이지런은 Zone 2, 인터벌은 Zone 4~5에서 실시합니다.',
        category: 'body',
        related: ['vo2max', 'easy-run', 'interval'],
    },
    {
        id: 'aerobic',
        term: '유산소 (Aerobic)',
        shortDesc: '산소를 사용하는 에너지 시스템',
        fullDesc: '산소를 사용하여 에너지를 생산하는 신체 시스템입니다. 마라톤은 99% 이상 유산소 운동이며, 유산소 능력이 곧 마라톤 능력입니다. 이지런과 롱런이 유산소 시스템을 발달시키는 핵심 훈련입니다.',
        category: 'body',
        related: ['vo2max', 'lsd', 'easy-run'],
    },
    {
        id: 'runners-knee',
        term: '러너스 니 (Runner\'s Knee)',
        shortDesc: '슬개대퇴 통증 증후군',
        fullDesc: '달리기 선수에게 가장 흔한 부상 중 하나로, 무릎 앞쪽 또는 주변에 통증이 발생합니다. 과도한 훈련량 증가, 부적절한 신발, 근력 부족 등이 원인입니다. 주간 훈련량을 10% 이상 급격히 늘리지 않는 것이 예방의 핵심입니다.',
        category: 'body',
        related: ['cross-training', 'ten-percent-rule'],
    },
    {
        id: 'cadence',
        term: '케이던스 / 피치 (Cadence)',
        shortDesc: '분당 걸음 수',
        fullDesc: '1분 동안의 총 걸음 수(양발 합산)입니다. 엘리트 러너는 보통 180spm(steps per minute) 전후이며, 초보 러너는 160~170spm인 경우가 많습니다. 케이던스를 높이면 보폭이 줄어들어 착지 충격이 감소하고, 부상 위험이 낮아지며, 달리기 효율이 향상됩니다.',
        category: 'body',
        related: ['pronation', 'strides'],
    },
    {
        id: 'pronation',
        term: '프로네이션 (Pronation)',
        shortDesc: '발의 안쪽 회전 움직임',
        fullDesc: '달릴 때 발이 지면에 닿으면서 안쪽으로 회전하는 자연스러운 움직임입니다. 정상 프로네이션(Neutral), 과도한 안쪽 회전(Over-pronation), 부족한 회전(Under-pronation/Supination)으로 구분됩니다. 자신의 프로네이션 유형에 맞는 러닝화를 선택하는 것이 부상 예방에 중요합니다.',
        category: 'body',
        related: ['runners-knee', 'carbon-plate'],
    },
    {
        id: 'plantar-fasciitis',
        term: '족저근막염 (Plantar Fasciitis)',
        shortDesc: '발바닥 통증을 일으키는 흔한 부상',
        fullDesc: '발바닥의 족저근막(발뒤꿈치에서 발가락까지 연결된 조직)에 염증이 생기는 질환입니다. 아침에 일어나서 첫 걸음에 심한 통증이 특징입니다. 과도한 훈련량, 부적절한 신발, 종아리 근육 유연성 부족이 주요 원인입니다. 스트레칭, 아이싱, 적절한 신발 선택으로 예방할 수 있습니다.',
        category: 'body',
        related: ['runners-knee', 'ten-percent-rule'],
    },
    {
        id: 'itbs',
        term: 'IT밴드 증후군 (ITBS)',
        shortDesc: '무릎 바깥쪽 통증',
        fullDesc: '장경인대(Iliotibial Band)가 무릎 바깥쪽 뼈와 마찰하면서 발생하는 통증입니다. 러너에게 두 번째로 흔한 부상으로, 내리막에서 특히 악화됩니다. 엉덩이 근력(특히 중둔근) 강화, 폼롤러 사용, 점진적 훈련량 증가로 예방할 수 있습니다.',
        category: 'body',
        related: ['runners-knee', 'cross-training'],
    },
    {
        id: 'doms',
        term: 'DOMS (지연성 근육통)',
        shortDesc: '운동 후 24~72시간 뒤 나타나는 근육통',
        fullDesc: 'Delayed Onset Muscle Soreness의 약자로, 강한 운동이나 익숙하지 않은 운동 후 24~72시간에 최고조에 달하는 근육통입니다. 근육 미세 손상에 의한 정상적인 반응이며, 시간이 지나면 자연 회복됩니다. 가벼운 리커버리 런이 회복에 도움될 수 있습니다.',
        category: 'body',
        related: ['recovery-run', 'easy-run'],
    },
    {
        id: 'overtraining',
        term: '과훈련 증후군 (Overtraining Syndrome)',
        shortDesc: '과도한 훈련으로 인한 만성 피로 상태',
        fullDesc: '회복 없이 과도한 훈련을 지속했을 때 나타나는 증상입니다. 기록 정체 또는 저하, 만성 피로, 수면 장애, 심박수 이상, 면역력 저하 등이 나타납니다. 회복에 수주~수개월이 걸릴 수 있어 예방이 중요합니다. 충분한 휴식일, 10% 룰 준수, 수면 관리가 핵심입니다.',
        category: 'body',
        related: ['ten-percent-rule', 'recovery-run', 'heart-rate-zone'],
    },
    {
        id: 'max-heart-rate',
        term: '최대심박수 (Max HR)',
        shortDesc: '운동 중 도달할 수 있는 최대 심박수',
        fullDesc: '심장이 1분 동안 뛸 수 있는 최대 횟수입니다. 간편 공식은 "220 - 나이"이지만 개인차가 큽니다. 정확한 측정은 전력 달리기 테스트나 의료기관 검사로 가능합니다. 심박 존 훈련의 기준이 되며, 이지런은 최대심박수의 60~70%, 인터벌은 90~95%에서 실시합니다.',
        category: 'body',
        related: ['heart-rate-zone', 'vo2max'],
    },
    {
        id: 'resting-heart-rate',
        term: '안정시심박수 (Resting HR)',
        shortDesc: '휴식 중 심박수',
        fullDesc: '완전한 휴식 상태에서의 분당 심박수입니다. 일반 성인은 60~80bpm이며, 훈련된 러너는 40~50bpm까지 낮아집니다. 유산소 체력의 지표로, 꾸준한 훈련으로 낮아집니다. 아침 기상 직후 측정이 가장 정확하며, 평소보다 높으면 피로 누적이나 컨디션 저하의 신호일 수 있습니다.',
        category: 'body',
        related: ['max-heart-rate', 'heart-rate-zone', 'overtraining'],
    },
    {
        id: 'glycogen',
        term: '글리코겐 (Glycogen)',
        shortDesc: '근육과 간에 저장된 탄수화물 에너지',
        fullDesc: '탄수화물이 근육과 간에 저장된 형태로, 달리기의 주요 에너지원입니다. 체내에 약 2,000kcal 정도 저장되며, 풀마라톤에서 약 2,500~3,000kcal가 필요하므로 고갈됩니다. 이것이 "벽"을 만나는 이유이며, 카보로딩과 레이스 중 에너지젤 섭취로 보충합니다.',
        category: 'body',
        related: ['wall', 'carb-loading', 'energy-gel'],
    },
    {
        id: 'shin-splints',
        term: '신 스플린트 (Shin Splints)',
        shortDesc: '정강이 통증',
        fullDesc: '정강이 앞쪽이나 안쪽에 통증이 발생하는 증상으로, 초보 러너에게 매우 흔합니다. 갑작스러운 훈련량 증가, 딱딱한 지면에서의 달리기, 낡은 신발 착용이 주요 원인입니다. 아이싱, 휴식, 점진적 훈련 증가로 관리하며, 지속되면 피로 골절 가능성을 확인해야 합니다.',
        category: 'body',
        related: ['ten-percent-rule', 'runners-knee'],
    },

    // Gear
    {
        id: 'carbon-plate',
        term: '카본 플레이트 슈즈',
        shortDesc: '탄소 섬유판이 내장된 레이싱 슈즈',
        fullDesc: '미드솔에 탄소 섬유 플레이트가 내장되어 추진력을 높여주는 경기용 러닝화입니다. 나이키 알파플라이, 아디다스 아디오스 프로 등이 대표적입니다. 마라톤 기록을 1~3% 향상시킬 수 있다는 연구 결과가 있으며, 현재 대부분의 엘리트 선수가 착용합니다.',
        category: 'gear',
    },
    {
        id: 'gps-watch',
        term: 'GPS 워치',
        shortDesc: 'GPS 기반 러닝 시계',
        fullDesc: 'GPS를 이용해 달리기 거리, 페이스, 심박수 등을 실시간으로 측정하는 시계입니다. 가민, 코로스, 폴라, 애플워치 등이 대표적이며, 훈련 관리와 레이스 페이스 유지에 필수적인 장비입니다.',
        category: 'gear',
        related: ['heart-rate-zone', 'cadence'],
    },
    {
        id: 'compression-wear',
        term: '컴프레션 웨어 (Compression Wear)',
        shortDesc: '착압 기능 스포츠 의류',
        fullDesc: '근육을 적절히 압박하여 혈액 순환을 돕고 근육 진동을 줄여주는 스포츠 의류입니다. 종아리 슬리브, 타이츠 등이 대표적입니다. 운동 중 피로 감소와 운동 후 회복 촉진 효과가 있다는 연구 결과가 있으며, 특히 장거리 레이스 후 회복용으로 많이 착용합니다.',
        category: 'gear',
        related: ['recovery-run', 'doms'],
    },
    {
        id: 'foam-roller',
        term: '폼롤러 (Foam Roller)',
        shortDesc: '근막 이완용 원통형 도구',
        fullDesc: '근육과 근막을 스스로 마사지(Self-Myofascial Release)할 수 있는 원통형 도구입니다. 달리기 후 종아리, 대퇴사두근, IT밴드 등을 풀어주는 데 효과적입니다. 근육 회복 촉진, 유연성 향상, 부상 예방에 도움되며, 러너의 필수 회복 도구로 자리잡았습니다.',
        category: 'gear',
        related: ['itbs', 'doms', 'recovery-run'],
    },
    {
        id: 'running-vest',
        term: '러닝 조끼 / 하이드레이션 팩',
        shortDesc: '물과 보급품을 넣는 러닝용 가방',
        fullDesc: '물병이나 수낭(하이드레이션 블래더), 에너지젤, 휴대폰 등을 넣고 달릴 수 있는 조끼형 가방입니다. 울트라마라톤이나 트레일러닝에서 필수 장비이며, 장거리 훈련에서도 유용합니다. 살로몬, 네이선 등이 대표적인 브랜드입니다.',
        category: 'gear',
        related: ['hydration', 'ultra-marathon', 'energy-gel'],
    },
    {
        id: 'headlamp',
        term: '헤드램프 (Headlamp)',
        shortDesc: '야간/새벽 달리기용 머리 조명',
        fullDesc: '이른 새벽이나 야간 달리기, 울트라마라톤 야간 구간에서 사용하는 머리에 착용하는 조명입니다. 200루멘 이상의 밝기와 가벼운 무게가 중요하며, 충전식이 편리합니다. 야간 대회에서는 필수 장비로 지정되는 경우가 많습니다.',
        category: 'gear',
        related: ['ultra-marathon'],
    },
    {
        id: 'anti-chafe',
        term: '안티 차핑 (Anti-Chafe)',
        shortDesc: '피부 쓸림 방지 제품',
        fullDesc: '장거리 달리기에서 피부끼리, 또는 피부와 의류가 반복적으로 마찰되어 발생하는 쓸림(chafing)을 방지하는 제품입니다. 바셀린, 바디글라이드 등이 대표적입니다. 겨드랑이, 허벅지 안쪽, 유두 부위에 주로 바르며, 풀마라톤 이상에서는 필수입니다.',
        category: 'gear',
        related: ['ultra-marathon'],
    },

    // Nutrition
    {
        id: 'carb-loading',
        term: '카보로딩 (Carb Loading)',
        shortDesc: '대회 전 탄수화물 저장량 극대화',
        fullDesc: '대회 2~3일 전부터 탄수화물 비중을 높인 식사를 하여 근육 내 글리코겐 저장량을 극대화하는 전략입니다. 하프마라톤 이상의 거리에서 효과적이며, "벽"을 만나는 시점을 늦출 수 있습니다. 밥, 파스타, 빵, 바나나 등이 대표적인 카보로딩 음식입니다.',
        category: 'nutrition',
        related: ['wall', 'taper'],
    },
    {
        id: 'energy-gel',
        term: '에너지젤 (Energy Gel)',
        shortDesc: '레이스 중 탄수화물 보충제',
        fullDesc: '레이스 중 빠르게 에너지를 보충할 수 있는 농축 탄수화물 제품입니다. 보통 45~60분 간격으로 섭취하며, 풀마라톤에서 3~5개를 사용합니다. 모엘, 구 에너지, SIS 등이 대표적이며, 대회 전 훈련에서 미리 테스트해보는 것이 중요합니다.',
        category: 'nutrition',
        related: ['wall', 'aid-station', 'carb-loading'],
    },
    {
        id: 'hydration',
        term: '수분 보충 (Hydration)',
        shortDesc: '운동 중/후 수분 섭취',
        fullDesc: '달리기 중 땀으로 잃는 수분을 보충하는 것입니다. 체중의 2% 이상 수분을 잃으면 성능이 저하됩니다. 갈증을 느끼기 전에 소량씩 자주 마시는 것이 좋으며, 장거리에서는 전해질(나트륨 등)도 함께 보충해야 합니다.',
        category: 'nutrition',
        related: ['aid-station', 'energy-gel', 'electrolytes'],
    },
    {
        id: 'electrolytes',
        term: '전해질 (Electrolytes)',
        shortDesc: '땀으로 손실되는 필수 미네랄',
        fullDesc: '나트륨, 칼륨, 마그네슘 등 체내 수분 균형과 근육 기능에 필수적인 미네랄입니다. 장거리 달리기에서 땀을 통해 대량 손실되며, 부족하면 근육 경련, 무기력, 심한 경우 저나트륨혈증(hyponatremia)이 발생합니다. 스포츠 음료, 전해질 타블렛, 소금 캡슐 등으로 보충합니다.',
        category: 'nutrition',
        related: ['hydration', 'aid-station'],
    },
    {
        id: 'runners-stomach',
        term: '러너스 스토마크 (Runner\'s Stomach)',
        shortDesc: '달리기 중 위장 장애',
        fullDesc: '달리기 중 발생하는 복통, 메스꺼움, 설사 등의 위장 증상입니다. 달리기 시 장으로의 혈류가 감소하고 장이 위아래로 흔들리면서 발생합니다. 레이스 2~3시간 전까지 식사를 마치고, 고지방/고섬유질 음식을 피하며, 에너지젤은 훈련에서 미리 테스트해보는 것이 예방법입니다.',
        category: 'nutrition',
        related: ['energy-gel', 'carb-loading'],
    },
    {
        id: 'caffeine',
        term: '카페인 (Caffeine)',
        shortDesc: '합법적 퍼포먼스 향상 보조제',
        fullDesc: '과학적으로 가장 많이 검증된 합법적 달리기 보조제입니다. 레이스 30~60분 전 체중 kg당 3~6mg 섭취 시 지구력과 집중력이 향상됩니다. 에너지젤에 카페인이 포함된 제품도 있으며, 레이스 후반부에 섭취하면 효과적입니다. 다만 평소 카페인에 민감한 사람은 주의가 필요합니다.',
        category: 'nutrition',
        related: ['energy-gel', 'runners-stomach'],
    },
];
