# Generated by Django 5.2.11 on 2026-06-13 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('urgent', '긴급'), ('notice', '공지'), ('racenews', '대회소식'), ('event', '이벤트')], default='notice', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('author', models.CharField(default='ENDUROHUB 운영팀', max_length=50)),
                ('pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('related_race', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notices',
                'ordering': ['-pinned', '-published_at'],
            },
        ),
    ]
