# Generated by Django 5.2.17 on 2026-08-18 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='관리용 이름')),
                ('active', models.BooleanField(default=False, verbose_name='게시')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='게시 시작')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='게시 종료')),
                ('placement', models.CharField(choices=[('home', '홈에서만'), ('all', '모든 페이지')], default='home', max_length=10, verbose_name='노출 위치')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('dismiss_days', models.PositiveSmallIntegerField(default=7, verbose_name='다시 보지 않기(일)')),
                ('tag', models.CharField(blank=True, default='이벤트', max_length=30, verbose_name='태그')),
                ('headline', models.TextField(verbose_name='헤드라인')),
                ('headline_accent', models.CharField(blank=True, default='', max_length=40, verbose_name='헤드라인 강조 단어')),
                ('subtitle', models.TextField(blank=True, default='', verbose_name='설명')),
                ('meta_period', models.CharField(blank=True, default='', max_length=40, verbose_name='메타 · 기간')),
                ('meta_winners', models.CharField(blank=True, default='', max_length=40, verbose_name='메타 · 당첨')),
                ('show_dday', models.BooleanField(default=True, verbose_name='마감 D-day 표시')),
                ('prize_image', models.ImageField(blank=True, null=True, upload_to='popups/%Y-%m/', verbose_name='경품 이미지')),
                ('prize_note', models.CharField(blank=True, default='', max_length=60, verbose_name='경품 부가설명')),
                ('prize_name', models.CharField(blank=True, default='', max_length=80, verbose_name='경품 이름')),
                ('prize_count', models.CharField(blank=True, default='', max_length=20, verbose_name='경품 수량')),
                ('cta_label', models.CharField(blank=True, default='자세히 보기', max_length=40, verbose_name='CTA 문구')),
                ('cta_url', models.CharField(blank=True, default='', help_text='비워 두면 연결된 공지사항 상세(/notice/<id>)로 이동합니다.', max_length=300, verbose_name='CTA 링크')),
                ('fine_period', models.CharField(blank=True, default='', max_length=80, verbose_name='세부 · 기간')),
                ('fine_announce', models.CharField(blank=True, default='', max_length=120, verbose_name='세부 · 발표')),
                ('fine_note', models.TextField(blank=True, default='', verbose_name='세부 · 유의사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popups', to='notices.notice', verbose_name='상세 공지사항')),
            ],
            options={
                'verbose_name': '팝업 배너',
                'verbose_name_plural': '팝업 배너',
                'db_table': 'notice_popups',
                'ordering': ['-priority', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PopupStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='순서')),
                ('title', models.CharField(max_length=80, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='notices.popup')),
            ],
            options={
                'verbose_name': '참여 단계',
                'verbose_name_plural': '참여 단계',
                'db_table': 'notice_popup_steps',
                'ordering': ['order', 'id'],
            },
        ),
    ]
