# Generated by Django 5.2.11 on 2026-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunSQL(
            sql="UPDATE user_profiles SET nickname = NULL WHERE nickname = '';",
            reverse_sql="UPDATE user_profiles SET nickname = '' WHERE nickname IS NULL;",
        ),
    ]
