# Generated by Django 5.2.11 on 2026-06-03 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('record_date', models.CharField(blank=True, default='', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'race_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
