# Generated by Django 5.2.11 on 2026-06-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_racerecord'),
        ('races', '0011_raceparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerecord',
            name='course_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='racerecord',
            name='is_personal_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='racerecord',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='races.race'),
        ),
    ]
