# Generated by Django 5.2.11 on 2026-02-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(max_length=10)),
                ('subscribed_sports', models.JSONField(blank=True, null=True)),
                ('subscribed_regions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_tokens',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('sport', models.CharField(max_length=20)),
                ('race_date', models.DateField()),
                ('race_end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('region', models.CharField(max_length=50)),
                ('distances', models.JSONField(blank=True, null=True)),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('entry_fee', models.JSONField(blank=True, null=True)),
                ('official_url', models.CharField(blank=True, max_length=500, null=True)),
                ('recap_url', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('source_url', models.CharField(blank=True, max_length=500, null=True)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=100, null=True)),
                ('organizer_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('organizer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('giveaways', models.JSONField(blank=True, null=True)),
                ('course_images', models.JSONField(blank=True, null=True)),
                ('giveaway_images', models.JSONField(blank=True, null=True)),
                ('course_image_uploads', models.JSONField(blank=True, null=True)),
                ('giveaway_image_uploads', models.JSONField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('locked_fields', models.JSONField(blank=True, null=True)),
                ('auto_update_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'races',
                'ordering': ['race_date'],
            },
        ),
        migrations.CreateModel(
            name='RacePendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='crawler', max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='races.race')),
            ],
            options={
                'db_table': 'race_pending_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('ip_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='races.race')),
            ],
            options={
                'db_table': 'race_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
