# Generated by Django 5.2.11 on 2026-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_racefavorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='racefavorite',
            new_name='race_favori_user_id_644d22_idx',
            old_name='race_favori_user_id_e8a1f2_idx',
        ),
        migrations.AddField(
            model_name='race',
            name='weather_forecast',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
