# Generated by Django 5.2.11 on 2026-04-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_add_weather_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
