# Generated by Django 5.2.11 on 2026-04-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_add_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='aid_stations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='course_difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='course_surface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='parking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='timing_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
