# Generated by Django 5.2.11 on 2026-06-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_add_at_a_glance_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('maybe', '관심'), ('confirmed_going', '참가 예정')], default='maybe', max_length=20)),
                ('planned_codes', models.JSONField(blank=True, default=list)),
                ('main_goal', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='races.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'race_participations',
                'indexes': [models.Index(fields=['user', '-updated_at'], name='race_partic_user_id_4e1e56_idx')],
                'unique_together': {('user', 'race')},
            },
        ),
    ]
